// examples/vue2/src/App.jsx
import { IconProvider } from '@twist-space/vue2-icons'
import { TiCheckCircleFilled, TiCat } from '@twist-space/vue2-icons/ti'
import './App.css'

const App = {
  name: 'App',
  render() {
    return (
      <div id='root'>
        <IconProvider size={60}>
          <TiCheckCircleFilled color="green" />
          <TiCat size={30} />
        </IconProvider>
      </div>
    )
  }
}

export default App

// examples/vue/src/App.vue
<script setup lang="ts">
import { IconProvider } from '@twist-space/vue3-icons'
import { TiCheckCircleFilled, TiCat } from '@twist-space/vue3-icons/ti'
import './style.css'
</script>

<template>
  <IconProvider :size="60">
    <TiCheckCircleFilled color="green" />
    <TiCat :size="30" />
  </IconProvider>
</template>
