// examples/vue/src/App.vue
<script setup lang="ts">
import { IconProvider } from '@twist-space/vue3-icons'
import { TiCheckCircleFilled, TiCat } from '@twist-space/vue3-icons/ti'
import './style.css'
</script>

<template>
  <IconProvider :size="60">
    <TiCheckCircleFilled color="green" />
    <TiCat :size="30" />
  </IconProvider>
</template>

// examples/react/src/App.tsx
import { IconProvider } from '@twist-space/react-icons'
import { TiCheckCircleFilled, TiCat } from '@twist-space/react-icons/ti'
import './App.css'

function App() {

  return (
    <IconProvider value={{size: 60}}>
      <TiCheckCircleFilled color='green' />
      <TiCat size={30} />
    </IconProvider>
  )
}

export default App
